export default {
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  RESET: "RESET",

  SET_INPUT_FIRSTNAME: "SET_INPUT_FIRSTNAME",
  SET_INPUT_LASTNAME: "SET_INPUT_LASTNAME",

  SET_INPUT_ID: "SET_INPUT_ID",

  RESET_INPUT: "RESET_INPUT",

  ADD_USER: "ADD_USER",
  DELETE_USER: "DELETE_USER",
  UPDATE_USER: "UPDATE_USER",
  CONFIRM_USER: "CONFIRM_USER",
};
